name: mlops-workshop-env
channels:
      - conda-forge
      - defaults
dependencies:
      - python=3.10.4
      - pip
      - notebook
      - ipykernel
      - pip:
              - azureml-core==1.43.0
              - azureml-mlflow==1.43.0.post1
              - flake8==4.0.1
              - isort==5.10.1
              - black==22.3.0
              - catboost==1.0.6
              - scikit-learn==1.1.1
              - mlflow==1.27.0
              - pandas==1.4.3
              - numpy==1.23.1
              - opencensus
              - opencensus-ext-azure
              - flask=1.1.2
